#!/bin/bash

# MongoDB Atlas Network Access Configuration
# This script helps you configure MongoDB to allow Vercel connections

echo "╔════════════════════════════════════════════════════════╗"
echo "║   MongoDB Atlas - Configure Network Access            ║"
echo "╚════════════════════════════════════════════════════════╝"
echo ""

echo "⚠️  IMPORTANT: Vercel serverless functions need access to MongoDB"
echo ""
echo "To allow Vercel to connect to your MongoDB Atlas cluster:"
echo ""
echo "1. Open: https://cloud.mongodb.com/"
echo "2. Select your cluster (cluster0)"
echo "3. Click 'Network Access' in the left sidebar"
echo "4. Click '+ ADD IP ADDRESS' button"
echo "5. In the dialog:"
echo "   • Select 'ALLOW ACCESS FROM ANYWHERE'"
echo "   • IP Address will auto-fill: 0.0.0.0/0"
echo "   • Comment: Vercel serverless functions"
echo "6. Click 'Confirm'"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🔒 SECURITY NOTE:"
echo "   For production, you should whitelist only Vercel's IP ranges:"
echo "   https://vercel.com/docs/concepts/functions/serverless-functions/regions"
echo ""
echo "   But for development, 0.0.0.0/0 (anywhere) is fine."
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
read -p "Press Enter after you've configured Network Access in MongoDB Atlas..."
echo ""
echo "✅ MongoDB Network Access should now be configured!"
echo ""
echo "You can verify by trying to connect:"
echo ""
echo "mongosh \"mongodb+srv://cluster0.07xptlx.mongodb.net/\" --apiVersion 1 --username kedarmanas171_db_user"
echo ""
